### ISSUE TITLE
Problema compilare

### ISSUE THREAD

**Issue by dajkazsolt** [etc-sodtr/Displaying-temperature#1]
Pentru a crea GUI-ul am folosit Embedded Wizzard Studio ( evaluation version).
Incerc de mai multe zile sa integrez GUI in RTOS cu Atollic Studio dar cand incerc sa compilez fisierele generate de catre Embedded Wizzard primes eroare "undefined reference to ..." functii ale GUI-ului.
Singurul raspuns la aceasta problema am gasit-o aici:
http://ask.embedded-wizard.de/446/using-stm32fx-build-environment-with-third-party-toolchain 

Aveti idee cum as putea integra functia de afisare?

**Comment by kcs** [comment]
Nu cunosc acest Atollic Studio, dar dacă are în spate un gcc, atunci poți să compilezi legând cu biblioteca de PlatformPackage din proiectul EmWi. Probabil există niște opțiuni de compilare și în Atollic Studio pentru a lega cu biblioteci externe. Dacă e cât inteligent (că aparent e bazat pe Eclipse) atunci poți pur și simplu să adaugi biblioteca ca și cum ai adăuga un fișier sursă existent (ceva de genul Add existing file)

**Comment by dajkazsolt** [comment]
Functiile care nu le gasea se aflau in fisierul ewrte.h.
Am inclus fisierul \PlatformPackage\RTE\libewrte.a si in setarile de librarie din mediu dar cand incerc sa compilez primesc eroarea : 
/arm-atollic-eabi/bin/ld.exe: cannot find -lC:\STM-RTOS\STM32F429I_Discovery_FreeRTOS_Simple_Demo\PlatformPackage\RTE\libewrte.a

Fisierul exista in folder. Aveti vreo idee unde am gresit sau cum pot rezolva problema ?

**Comment by kcs** [comment]
ceva nu e bine cu opțiunea aia -l_cale-completă_
ori ar trebui să apară -L_director_ și -lewrte ori -l:_cale-completă_

acolo la setările de bibliotecă vezi că ar trebui să fie ceva pentru cale către biblioteci (opțiune separată) în cale să introduci numai directorul unde e biblioteca (PlatformPackage/)
iar la biblioteci să adaugi numai ewrte (fără lib în față și fără extensie)
dacă nu merge așa, atunci lasă cu calea completă și cu denumirea completă dar pune : în față

**Comment by dajkazsolt** [comment]
Va multumesc pentru ajutor. Programul compileaza, au mai aparut cateva erori dar am reusit sa le rezolv.
